//! The `staxtrace.resume/1` envelope — `stax resume --json`.
//!
//! A port of the payload assembled in `python-legacy: cli.py:resume_cmd`
//! (the `payload: dict[str, Any]` literal and the loop that fills
//! `providers`). Unlike `staxtrace.memory/1` this contract has **no
//! shipped golden pack and no JSON-Schema** — it is pinned only by
//! `tests/python-legacy: cli/test_resume_cmd.py::test_json_envelope_shape`,
//! which asserts the schema tag, `path`, provider sort order and the session
//! key set. The goldens under `tests/goldens/rust-campaign-added/resume-v1/` are therefore
//! rust-campaign-added: generated by running the *Python* CLI over the seed
//! that test uses, so they are Python bytes, not this port's opinion.
//!
//! Key order, which is the contract:
//!
//! * envelope — `schema`, `path`, `providers`, then `provider_filter` and
//!   `unmatched_providers` when `--provider` narrowed the query (Python inserts
//!   them after `providers` is created but before it is filled);
//! * provider block — `provider`, `resume`, `sessions`;
//! * session — `session_id`, `first_ts`, `last_ts`, `message_count`, `project`,
//!   `project_path`, `resume_command` (the `{**sess, "resume_command": cmd}`
//!   splat puts the rendered command last);
//! * resume template — verbatim from `adapters/capabilities.json`, whose entries
//!   read `command`, `scope`, `note` (grok only), `verified`.
//!
//! `resume` is `null` for an agent with no known resume command, and every
//! `resume_command` in such a block is `null` too: "agents whose CLI has no
//! known resume command still list their session ids", never an invented one.

use serde::ser::{SerializeMap, Serializer};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::envelope::{EnvelopeError, render, render_line};
use crate::pyjson;

/// The frozen contract id.
pub const RESUME_SCHEMA: &str = "staxtrace.resume/1";

/// Bumps only on a breaking change to the envelope.
pub const RESUME_SCHEMA_VERSION: u32 = 1;

/// Session/resume ids for every coding agent under a path.
#[derive(Debug, Clone, PartialEq)]
pub struct ResumeEnvelope {
    pub schema: String,
    /// The resolved query path (`resume_candidates` resolves it, not the shell).
    pub path: String,
    /// One block per provider, sorted by provider name.
    pub providers: Vec<ProviderBlock>,
    /// Echo of `--provider`, verbatim and in the order given — present only
    /// when the flag was used.
    pub provider_filter: Option<Vec<String>>,
    /// Requested providers with no sessions under this path; present only when
    /// `--provider` was used AND something went unmatched.
    pub unmatched_providers: Option<Vec<String>>,
    /// Additive fields from a newer producer, emitted last.
    pub extra: Map<String, Value>,
}

/// One coding agent's sessions under the queried path.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProviderBlock {
    pub provider: String,
    /// The capability template, or `null` when the CLI has no known resume.
    pub resume: Option<ResumeTemplate>,
    pub sessions: Vec<ResumeSession>,
}

/// A resume-command template — data, read straight out of
/// `adapters/capabilities.json`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResumeTemplate {
    /// e.g. `claude --resume {session_id}`, or `grok --continue`.
    pub command: String,
    /// `session` (per-id) or `latest` (resumes the newest session in the cwd).
    pub scope: String,
    /// Only grok carries one today.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// How the command was checked, e.g. "claude --help on a real install".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified: Option<String>,
    /// Additive keys a later capabilities.json adds, emitted last.
    #[serde(flatten)]
    pub extra: Map<String, Value>,
}

/// One session, with its rendered resume invocation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResumeSession {
    pub session_id: String,
    pub first_ts: Option<String>,
    pub last_ts: Option<String>,
    pub message_count: i64,
    /// The project slug.
    pub project: String,
    /// The stored path, or `null` — slug decode is lossy, so Python never
    /// fabricates one and neither does this.
    pub project_path: Option<String>,
    /// `null` for a `latest`-scope or unknown agent.
    pub resume_command: Option<String>,
    #[serde(flatten)]
    pub extra: Map<String, Value>,
}

impl ResumeTemplate {
    /// Render `command` for a session id, the way `resume_cmd` does.
    ///
    /// `None` unless the template is `session`-scoped: a `latest`-scope agent
    /// has no per-session invocation, so inventing one would be a lie.
    #[must_use]
    pub fn render_command(&self, session_id: &str) -> Option<String> {
        if self.scope != "session" {
            return None;
        }
        Some(self.command.replace("{session_id}", session_id))
    }
}

impl Serialize for ResumeEnvelope {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let len = 3
            + usize::from(self.provider_filter.is_some())
            + usize::from(self.unmatched_providers.is_some())
            + self.extra.len();
        let mut map = serializer.serialize_map(Some(len))?;
        map.serialize_entry("schema", &self.schema)?;
        map.serialize_entry("path", &self.path)?;
        map.serialize_entry("providers", &self.providers)?;
        if let Some(filter) = &self.provider_filter {
            map.serialize_entry("provider_filter", filter)?;
        }
        if let Some(unmatched) = &self.unmatched_providers {
            map.serialize_entry("unmatched_providers", unmatched)?;
        }
        for (key, value) in &self.extra {
            map.serialize_entry(key, value)?;
        }
        map.end()
    }
}

impl ResumeEnvelope {
    /// A new envelope for `path` with no providers and no filter echo.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            schema: RESUME_SCHEMA.to_owned(),
            path: path.into(),
            providers: Vec::new(),
            provider_filter: None,
            unmatched_providers: None,
            extra: Map::new(),
        }
    }

    /// See [`render`].
    #[must_use]
    pub fn render(&self) -> String {
        render(self)
    }

    /// See [`render_line`] — the exact `resume --json` stdout.
    #[must_use]
    pub fn render_line(&self) -> String {
        render_line(self)
    }

    /// Parse `resume --json` stdout (trailing newline tolerated).
    ///
    /// # Errors
    ///
    /// [`EnvelopeError`] for malformed JSON or a missing/mistyped field.
    pub fn from_json(text: &str) -> Result<Self, EnvelopeError> {
        Self::from_value(pyjson::loads(text)?)
    }

    /// Parse an already-decoded envelope.
    ///
    /// # Errors
    ///
    /// [`EnvelopeError`] for a missing or mistyped field.
    pub fn from_value(value: Value) -> Result<Self, EnvelopeError> {
        let Value::Object(mut map) = value else {
            return Err(EnvelopeError::NotAnObject);
        };
        let schema = match map.shift_remove("schema") {
            Some(Value::String(text)) => text,
            Some(_) => {
                return Err(EnvelopeError::WrongType {
                    field: "schema",
                    want: "a string",
                });
            }
            None => return Err(EnvelopeError::Missing("schema")),
        };
        let path = match map.shift_remove("path") {
            Some(Value::String(text)) => text,
            Some(_) => {
                return Err(EnvelopeError::WrongType {
                    field: "path",
                    want: "a string",
                });
            }
            None => return Err(EnvelopeError::Missing("path")),
        };
        let providers_raw = map
            .shift_remove("providers")
            .ok_or(EnvelopeError::Missing("providers"))?;
        let providers: Vec<ProviderBlock> =
            serde_json::from_value(providers_raw).map_err(|_| EnvelopeError::WrongType {
                field: "providers",
                want: "an array of provider blocks",
            })?;
        let provider_filter = take_string_list(&mut map, "provider_filter")?;
        let unmatched_providers = take_string_list(&mut map, "unmatched_providers")?;
        Ok(Self {
            schema,
            path,
            providers,
            provider_filter,
            unmatched_providers,
            extra: map,
        })
    }
}

fn take_string_list(
    map: &mut Map<String, Value>,
    field: &'static str,
) -> Result<Option<Vec<String>>, EnvelopeError> {
    match map.shift_remove(field) {
        None => Ok(None),
        Some(value) => {
            serde_json::from_value(value)
                .map(Some)
                .map_err(|_| EnvelopeError::WrongType {
                    field,
                    want: "an array of strings",
                })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn claude_template() -> ResumeTemplate {
        ResumeTemplate {
            command: "claude --resume {session_id}".to_owned(),
            scope: "session".to_owned(),
            note: None,
            verified: Some("claude --help on a real install, 2026-07-10".to_owned()),
            extra: Map::new(),
        }
    }

    #[test]
    fn schema_is_versioned() {
        assert_eq!(RESUME_SCHEMA, "staxtrace.resume/1");
        assert_eq!(
            RESUME_SCHEMA,
            format!("staxtrace.resume/{RESUME_SCHEMA_VERSION}")
        );
    }

    #[test]
    fn session_scope_renders_the_real_invocation() {
        assert_eq!(
            claude_template().render_command("cx-1").as_deref(),
            Some("claude --resume cx-1")
        );
    }

    #[test]
    fn latest_scope_invents_nothing() {
        let grok = ResumeTemplate {
            command: "grok --continue".to_owned(),
            scope: "latest".to_owned(),
            note: Some("no id-based resume in the grok CLI".to_owned()),
            verified: None,
            extra: Map::new(),
        };
        assert_eq!(grok.render_command("gr-1"), None);
    }

    #[test]
    fn envelope_key_order_is_schema_path_providers_then_the_filter_echo() {
        let mut env = ResumeEnvelope::new("/Users/t/my_ws");
        env.provider_filter = Some(vec!["codex".to_owned()]);
        env.unmatched_providers = Some(vec!["nope".to_owned()]);
        let parsed = pyjson::loads(&env.render()).expect("valid JSON");
        let keys: Vec<&str> = parsed
            .as_object()
            .expect("object")
            .keys()
            .map(String::as_str)
            .collect();
        assert_eq!(
            keys,
            [
                "schema",
                "path",
                "providers",
                "provider_filter",
                "unmatched_providers"
            ]
        );
    }

    #[test]
    fn the_filter_echo_is_absent_without_the_flag() {
        let env = ResumeEnvelope::new("/Users/t");
        assert_eq!(
            env.render(),
            "{\n  \"schema\": \"staxtrace.resume/1\",\n  \"path\": \"/Users/t\",\n  \"providers\": []\n}"
        );
    }

    #[test]
    fn session_key_order_matches_the_python_splat() {
        let block = ProviderBlock {
            provider: "claude".to_owned(),
            resume: Some(claude_template()),
            sessions: vec![ResumeSession {
                session_id: "cl-1".to_owned(),
                first_ts: Some("2026-07-01T10:00:00Z".to_owned()),
                last_ts: Some("2026-07-01T10:00:00Z".to_owned()),
                message_count: 142,
                project: "-Users-t-my-ws".to_owned(),
                project_path: None,
                resume_command: Some("claude --resume cl-1".to_owned()),
                extra: Map::new(),
            }],
        };
        let parsed = pyjson::loads(&render(&block)).expect("valid JSON");
        let obj = parsed.as_object().expect("object");
        assert_eq!(
            obj.keys().map(String::as_str).collect::<Vec<_>>(),
            ["provider", "resume", "sessions"]
        );
        let sess = obj["sessions"][0].as_object().expect("object");
        assert_eq!(
            sess.keys().map(String::as_str).collect::<Vec<_>>(),
            [
                "session_id",
                "first_ts",
                "last_ts",
                "message_count",
                "project",
                "project_path",
                "resume_command"
            ]
        );
        // `note` is omitted, not emitted as null — capabilities.json has no key
        // there for claude and json.dumps would show one if we invented it.
        let template = obj["resume"].as_object().expect("object");
        assert_eq!(
            template.keys().map(String::as_str).collect::<Vec<_>>(),
            ["command", "scope", "verified"]
        );
    }

    #[test]
    fn round_trip_preserves_unknown_fields() {
        let text = concat!(
            "{\n  \"schema\": \"staxtrace.resume/1\",\n",
            "  \"path\": \"/w\",\n  \"providers\": [],\n",
            "  \"x_future\": {\n    \"added_later\": [\n      1,\n      2\n    ]\n  }\n}"
        );
        let env = ResumeEnvelope::from_json(text).expect("parses");
        assert_eq!(env.render(), text);
    }

    #[test]
    fn a_missing_path_is_an_error_not_an_empty_string() {
        let err = ResumeEnvelope::from_value(json!({"schema": "staxtrace.resume/1"}))
            .expect_err("path is required");
        assert!(matches!(err, EnvelopeError::Missing("path")), "{err}");
    }
}
