#!/usr/bin/env bash
# Build the wave-9 wasm artifact and its two JS glues, and record the size.
#
# Outputs (all generated, none committed):
#   rust/demo/pkg/       --target web     — what index.html loads
#   rust/demo/pkg-node/  --target nodejs  — what rust/wasm-differ.sh drives
#   rust/demo/SIZE.md    the measured bytes plus the commands that produced them
#
# Two tools are needed and neither is on a stock box; both are pointed at by an
# environment variable so nothing is hard-coded to one machine:
#
#   STAX_WASI_SDK    a clang that targets wasm32. `sqlite-wasm-rs` compiles
#                    sqlite3.c, and this box has no clang at all
#                    (/usr/lib/llvm-10 ships libraries only). wasi-sdk is used
#                    purely as a C compiler: the artifact targets
#                    wasm32-unknown-unknown and imports no WASI syscall.
#                    Get it: https://github.com/WebAssembly/wasi-sdk/releases
#   STAX_WASM_BINDGEN  the `wasm-bindgen` CLI, version-matched to the
#                    wasm-bindgen crate in Cargo.lock (0.2.126). Either the
#                    release tarball or `cargo install wasm-bindgen-cli`.
#
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
RUST_DIR="$(cd "$HERE/.." && pwd)"

WASI_SDK="${STAX_WASI_SDK:-}"
BINDGEN="${STAX_WASM_BINDGEN:-$(command -v wasm-bindgen || true)}"

if [ -z "$WASI_SDK" ] || [ ! -x "$WASI_SDK/bin/clang" ]; then
    echo "build.sh: set STAX_WASI_SDK to an unpacked wasi-sdk (needs bin/clang)." >&2
    echo "  https://github.com/WebAssembly/wasi-sdk/releases  (33.0 is what wave 9 measured)" >&2
    exit 2
fi
if [ -z "$BINDGEN" ] || [ ! -x "$BINDGEN" ]; then
    echo "build.sh: set STAX_WASM_BINDGEN to a wasm-bindgen 0.2.126 binary." >&2
    echo "  cargo install wasm-bindgen-cli --version 0.2.126" >&2
    exit 2
fi

WANT="$(grep -A1 '^name = "wasm-bindgen"$' "$RUST_DIR/Cargo.lock" | sed -n 's/^version = "\(.*\)"$/\1/p' | head -1)"
HAVE="$("$BINDGEN" --version | awk '{print $2}')"
if [ -n "$WANT" ] && [ "$WANT" != "$HAVE" ]; then
    # A mismatch here does not fail the build, it fails at *runtime* with an
    # unhelpful import error — so it fails here instead.
    echo "build.sh: wasm-bindgen CLI is $HAVE but Cargo.lock pins $WANT." >&2
    exit 2
fi

export CC_wasm32_unknown_unknown="$WASI_SDK/bin/clang"
export AR_wasm32_unknown_unknown="$WASI_SDK/bin/llvm-ar"

cd "$RUST_DIR"
echo "==> cargo build -p stax-wasm --target wasm32-unknown-unknown --release"
cargo build -p stax-wasm --target wasm32-unknown-unknown --release

RAW="$RUST_DIR/target/wasm32-unknown-unknown/release/stax_wasm.wasm"
echo "==> wasm-bindgen --target web    -> demo/pkg"
"$BINDGEN" --target web --out-dir "$HERE/pkg" "$RAW"
echo "==> wasm-bindgen --target nodejs -> demo/pkg-node"
"$BINDGEN" --target nodejs --out-dir "$HERE/pkg-node" "$RAW"

# The page loads the wasm from an inlined base64 string rather than fetching it.
# That is what lets index.html keep `connect-src 'none'` in its CSP — the
# strictest possible statement of "nothing leaves this tab" — instead of
# loosening it to 'self' just so wasm-bindgen's own `fetch()` can run.
echo "==> inlining the wasm as base64 -> demo/pkg/stax_wasm_inline.js"
python3 "$HERE/inline_wasm.py" "$HERE/pkg/stax_wasm_bg.wasm" "$HERE/pkg/stax_wasm_inline.js"

raw_bytes=$(stat -c%s "$RAW")
inline_bytes=$(stat -c%s "$HERE/pkg/stax_wasm_inline.js")
bg_bytes=$(stat -c%s "$HERE/pkg/stax_wasm_bg.wasm")
gz_bytes=$(gzip -9 -c "$HERE/pkg/stax_wasm_bg.wasm" | wc -c)
glue_bytes=$(stat -c%s "$HERE/pkg/stax_wasm.js")

opt_note="\`wasm-opt\` is NOT installed on this box, so nothing here is post-processed — these are raw LLVM+lto outputs. A \`wasm-opt -Oz\` pass typically takes another 10-20%; the number is not claimed because it was not run."
if command -v wasm-opt >/dev/null 2>&1; then
    opt_note="\`wasm-opt\` IS available ($(wasm-opt --version)); re-measure with it before quoting a shipping size."
fi

cat > "$HERE/SIZE.md" <<EOF
# stax-wasm — measured size

Regenerated by \`rust/demo/build.sh\`; do not hand-edit. Every number below is
\`stat -c%s\` on the artifact named beside it.

    cargo build -p stax-wasm --target wasm32-unknown-unknown --release
    wasm-bindgen --target web --out-dir rust/demo/pkg \\
        rust/target/wasm32-unknown-unknown/release/stax_wasm.wasm

| artifact | bytes | KiB |
|---|---:|---:|
| \`target/wasm32-unknown-unknown/release/stax_wasm.wasm\` (cargo) | $raw_bytes | $((raw_bytes / 1024)) |
| \`demo/pkg/stax_wasm_bg.wasm\` (after wasm-bindgen) | $bg_bytes | $((bg_bytes / 1024)) |
| \`demo/pkg/stax_wasm_bg.wasm\`, gzip -9 (what a server sends) | $gz_bytes | $((gz_bytes / 1024)) |
| \`demo/pkg/stax_wasm.js\` (glue) | $glue_bytes | $((glue_bytes / 1024)) |
| \`demo/pkg/stax_wasm_inline.js\` (the same wasm as base64, so the page fetches nothing) | $inline_bytes | $((inline_bytes / 1024)) |

That payload contains a whole SQLite (FTS5, math functions, rtree, the
dbstat/bytecode vtabs — \`sqlite-wasm-rs\`'s \`FULL_FEATURED\` set), rusqlite,
\`stax-core\`'s query layer and \`stax-memory\`'s envelope writer. For scale: the
React dashboard this project already ships is an order of magnitude larger.

Toolchain: rustc $(rustc --version | awk '{print $2}'), wasm-bindgen $HAVE,
$(basename "$WASI_SDK") for the C half. Profile: workspace \`[profile.release]\`
— \`lto = true\`, \`codegen-units = 1\`.

$opt_note
EOF

echo
cat "$HERE/SIZE.md"
