#!/usr/bin/env python3
"""Emit the wasm module as a base64 ES-module export.

Called by `build.sh`. The page imports the result instead of fetching
`stax_wasm_bg.wasm`, which is what allows `index.html` to keep
`connect-src 'none'` in its Content-Security-Policy: with no fetch, XHR,
WebSocket or beacon permitted at all, "nothing leaves this tab" stops being a
claim in prose and becomes something the browser enforces.

Cost: base64 is 4/3 of the binary, and the browser spends ~20 ms in `atob`.
For a demo whose entire point is the privacy property, that is a good trade.
"""

from __future__ import annotations

import base64
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: inline_wasm.py <in.wasm> <out.js>", file=sys.stderr)
        return 2
    source, destination = Path(argv[1]), Path(argv[2])
    encoded = base64.b64encode(source.read_bytes()).decode("ascii")
    destination.write_text(
        "// GENERATED by rust/demo/build.sh — the wasm module, inlined so the\n"
        "// page never fetches anything. Do not edit.\n"
        f'export const WASM_BASE64 = "{encoded}";\n',
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
