//! Compile `stackunderflow/static/` into the binary.
//!
//! # Why this exists
//!
//! Until wave-10 item 2c the server read the React build off disk at RUNTIME —
//! `AppState::static_dir()` was `package_dir.join("static")`, and
//! `package_dir` defaulted to the checkout this crate was compiled in. A
//! machine running only the Rust binaries therefore still needed the
//! `stackunderflow` package tree present, which is exactly what
//! `docs/specs/decommission-report.md` §4.3 named as the blocker to deleting
//! it. Embedding closes that: the bundle travels inside `stax-server`.
//!
//! # Why a `build.rs` and not `rust-embed`
//!
//! Measured before taking, and the measurement did **not** say what it was
//! expected to: `cargo tree -i rust-embed` shows `rust-embed 8.12.0` is
//! already a compiled dependency of this crate, arriving through `age` →
//! `stax-sync`. Taking it directly would cost zero new packages. It was still
//! declined, for two reasons that survive that:
//!
//! 1. Without the `debug-embed` feature its derive reads the folder off disk in
//!    debug builds, so `cargo test` would exercise a different path from a
//!    release server — on the one crate whose point is that there is no disk.
//!    Forcing the feature means changing how `age` builds to serve this module.
//! 2. It replaces the smallest part. The table and the lookup are this file
//!    plus a `binary_search_by_key`; the directory `307`, the trailing-slash
//!    rule, the `405` shape and the header set still have to be written by hand
//!    against `ServeDir`'s measured behaviour either way.
//!
//! Full accounting in `rust/PACKAGING-STANDALONE.md` §2.
//!
//! # The generated table
//!
//! One `include_bytes!` per file under `stackunderflow/static/`, keyed by the
//! path relative to that directory with `/` separators — `favicon.ico`,
//! `react/index.html`, `react/assets/index-C5IztddV.js`, … — sorted by key so
//! `assets::get` can binary-search and so the generated file is deterministic.
//!
//! `include_bytes!` (not a `std::fs::read` into `OUT_DIR`) is deliberate: it is
//! the same mechanism `stax_etl::stats::dataset` uses for `models.toml` and
//! `stax_core::schema` uses for the migrations, and it makes the compiler,
//! rather than this script, the thing that fails when a file goes missing.
//!
//! # A missing bundle is a build failure
//!
//! Same rule as `models.toml`: a checkout without `stackunderflow/static/`
//! fails to compile rather than producing a server that 404s its own
//! dashboard. `ci.sh`'s gate-0 extraction set carries the directory for this
//! reason.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    // …/rust/crates/stax-server → …/stackunderflow/static
    let root = manifest.join("../../assets/static");
    let root = root.canonicalize().unwrap_or_else(|err| {
        panic!(
            "the checked-in React build is not at {} ({err}). It is the parity \
             oracle and it is compiled into this binary; a checkout without it \
             cannot build a dashboard. See build.rs.",
            root.display()
        )
    });

    let mut files = Vec::new();
    collect(&root, &root, &mut files);
    files.sort();
    assert!(
        !files.is_empty(),
        "{} is empty — nothing to serve",
        root.display()
    );

    let mut out = String::with_capacity(files.len() * 128);
    out.push_str(
        "// @generated by build.rs — do not edit.\n\
         /// Every file under `stackunderflow/static/`, sorted by key.\n\
         pub(crate) static EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for (key, path) in &files {
        writeln!(
            out,
            "    ({key:?}, include_bytes!({:?})),",
            path.to_string_lossy()
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(
        std::env::var_os("OUT_DIR").expect("cargo always sets OUT_DIR for a build script"),
    )
    .join("static_assets.rs");
    std::fs::write(&dest, out).unwrap_or_else(|err| panic!("writing {}: {err}", dest.display()));

    // Re-run when a file changes AND when one is added or removed: cargo
    // watches directories as well as files, so the root covers the second case
    // and the per-file lines cover the first through symlinks and edits.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", root.display());
    for (_, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

/// Depth-first walk, collecting `(key, absolute path)` pairs.
///
/// Directories are recursed; anything that is not a regular file (a symlink to
/// nowhere, a socket) is skipped rather than failing the build — the bundle is
/// a build output and the only thing in it is files.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries =
        std::fs::read_dir(dir).unwrap_or_else(|err| panic!("reading {}: {err}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|err| panic!("reading {}: {err}", dir.display()));
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let relative = path
                .strip_prefix(root)
                .unwrap_or_else(|_| panic!("{} escaped {}", path.display(), root.display()));
            let key = relative
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((key, path));
        }
    }
}
