//! The wasm32 query engine: read-only core in the browser, no watcher.
//!
//! Charter (`docs/specs/rust-port.md` §3): expose the read-only half of
//! `stax-core` compiled to wasm32 so a `store.db` dropped on a web page answers
//! queries locally — the strongest form of the privacy pitch (§7). No watcher,
//! no writer, no filesystem, and — the part that is checkable rather than
//! promised — **no network**: this crate's wasm artifact imports nothing but
//! `wasm-bindgen`'s own JS glue, and `rust/demo/index.html` pins a CSP with
//! `connect-src 'none'`.
//!
//! # The SQLite decision, and why it went this way
//!
//! §6 pinned the risk honestly: "wasm32 needs sqlite compiled to wasm (official
//! build / wa-sqlite bridge). If it fights back, wave 9 falls back to a
//! WASM-native read layer over exported pages." Three candidates were on the
//! table; the choice is the one that keeps the *queries* shared.
//!
//! 1. **sql.js / wa-sqlite (JS-side SQLite), Rust orchestrating.** Rejected.
//!    The moment SQLite lives in JS, the SQL has to be re-expressed in JS too —
//!    and the SQL *shapes* are the port's most load-bearing artifact (§6b: the
//!    list-subquery idiom and the hoisted `json_extract` are the difference
//!    between 9 ms and 912 ms on the partitioned `messages` view). A second,
//!    hand-written `search_past_decisions` in JavaScript would diverge the week
//!    after it shipped, and no differ would be watching it.
//! 2. **A WASM-native page reader over exported pages** (§6's own fallback).
//!    Rejected as unnecessary: it re-implements a b-tree engine to avoid a
//!    problem that turned out not to exist.
//! 3. **`sqlite-wasm-rs` under rusqlite** — CHOSEN. sqlite3.c compiled for
//!    `wasm32-unknown-unknown` with `SQLITE_OS_OTHER` + a musl shim, exposing
//!    the same C symbols `libsqlite3-sys` would, so **rusqlite is unchanged and
//!    `stax_core::queries` compiles as-is**. `stax memory decisions` in a
//!    browser tab runs the same statements, in the same order, against the same
//!    schema as the CLI. FTS5, math functions and the `dbstat` / `bytecode`
//!    vtabs are all compiled in.
//!
//! The wiring cost was zero manifest churn, which is worth recording because it
//! contradicts what the spec expected: rusqlite 0.40's default features include
//! `ffi-sqlite-wasm-rs`, and its `libsqlite3-sys` dependency is *optional* under
//! `cfg(all(target_family = "wasm", target_os = "unknown"))`. The workspace's
//! `features = ["bundled"]` forwards only through `libsqlite3-sys?/…`, so on
//! wasm32 it is inert — no `[target.…]` table in `stax-core`, no workspace
//! manifest edit, no feature-unification trap. (ARCHITECT-STATE finding 7
//! called this: "rusqlite 0.40 ships wasm32 FFI first-class".)
//!
//! ## Toolchain, stated because it is not on a stock box
//!
//! `sqlite-wasm-rs` compiles C, so the build needs a clang that targets wasm32.
//! There is none on the campaign machine (`/usr/lib/llvm-10` ships libraries
//! only), so the build uses a downloaded **wasi-sdk 33** clang, pointed at by
//! `CC_wasm32_unknown_unknown` / `AR_wasm32_unknown_unknown`.
//! `rust/demo/build.sh` is the whole recipe. Nothing about the *artifact*
//! depends on wasi-sdk — the output targets `wasm32-unknown-unknown` and
//! imports no WASI syscall — it is a build-time C compiler and nothing more.
//!
//! ## Size, measured
//!
//! `rust/demo/SIZE.md` carries the numbers and the commands that produced them,
//! regenerated by `rust/demo/build.sh` so the number in the tree is never a
//! number someone typed. Headline at wave 9: **2,164,469 bytes** (2.06 MiB) of
//! `wasm-bindgen` output, **815 KiB gzipped** — which is what a server actually
//! sends — plus 11.6 KiB of JS glue. Un-post-processed: `wasm-opt` is not
//! installed on this box and the script says so rather than pretending.
//!
//! ## The three things the browser cannot do
//!
//! Recorded as divergences rather than hidden: no `stat` (DIV-335 — the caller
//! declares whether `memory sessions`' target is a file), no cwd (the caller
//! passes one, and an empty one means "every project"), no clock (JS passes
//! `now_epoch`, which the ranker already took as an injected parameter — the
//! campaign's injected-clock law paid for itself here).

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod db;
pub mod verbs;

#[cfg(target_arch = "wasm32")]
mod js;
